### ISSUE TITLE
Validator not recognized (and chain `bitcannadevnet` neither)

### ISSUE THREAD

**Issue by RaulBernal** [eco-stake/validator-registry#2666]
Hello; I provide this data: 

https://github.com/eco-stake/validator-registry/blob/master/Pandora/chains.json

that should match with: 

https://testnet.restake.app/bitcannadevnet/bcnavaloper153hxvnx24h07aptul43fsuyeq7kgt2erqad6xy

But this is my output when I run the `restake` app:
```
[06:59:20.645] ⚛
[06:59:20.729] Failed with error: bitcannadevnet not found in Chain Registry
[06:59:20.730] Autostake failed

```
And this is the output of the RPC proxy connection at Cosmos Directory:
https://testnet.cosmos.directory/bitcannadevnet
`Chain not found`

**Comment by RaulBernal** [comment]
My config file: 
```
cat src/networks.local.json
{
	"bitcanna-dev-1": {
		"prettyName": "BitCanna devnet-1",
		"restUrl": [
			"https://lcd-testnet.bitcanna.io/"
		],
		"name": "bitcannadevnet",
		"image": "https://github.com/cosmostation/cosmostation_token_resource/blob/master/chains/logo/v2/bitcanna.png",
		"testnet": false,
		"gasPrice": "0.001ubcna",
		"gasPriceStep": {
			"low": 0.001,
			"average": 0.01,
			"high": 0.05
		},
		"autostake": {
			"batchTxs": 50,
			"batchQueries": 50,
			"delegatorTimeout": 5000
		}
	}
}```

**Comment by tombeynon** [comment]
Hey Raul! Couple changes needed here:

1. The `name` in validator registry needs to match the directory in Chain Registry (i.e. bitcannadevnet): https://github.com/eco-stake/validator-registry/blob/master/Pandora/chains.json#L6
2. your networks.local.json needs to use the same `bitcannadevnet` instead of `bitcanna-dev-1`
3. your networks.local.json should specify `"testnet": true` so it checks testnet.cosmos.directory instead of the mainnet site.

**Comment by RaulBernal** [comment]
Done! Let's see :)
